# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd69b3e708f4b9cb1b4cbacd6b3a122544a6153553d3d237ab4832d6a69c8fbbe3299d8156e0f043e05da343ffa2b3f192484c9fac16d3d946691f39f5e79ef8

test:
  secret_key_base: 64e9aabfddb557d07922e9808b36e340ec57029e83f15a66154f878edaa3ae25ea09f430131decb75fefe2038cfa26cd5252d91b50e5c40368296aace1e1ed29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
